### ISSUE TITLE
Optimise for sharing on social media

### ISSUE THREAD

**Issue by claratee** [ResilienceWeb/resilience-web#118]
If its possible to optimise the sharing of links from Resilience Web pages on social media, like twitter, facebook etc, that would be awesome. opengraph standard - markup image and description 

expected: automatically include image and excerpt (up to the character limit of the platform) in the preview.  
actual: no image or exerpt. eg https://twitter.com/CamResiliWeb

ps the image seems to come through on org detail pages, which is good.

**Comment by DinerIsmail** [comment]
Sure, it's already done for individual listing pages but it's not yet done for sharing a web. I'll pick this up to work on this month

**Comment by DinerIsmail** [comment]
This is now done ✅ 
![CleanShot 2023-11-04 at 15 48 03](https://github.com/ResilienceWeb/resilience-web/assets/4760294/8bfb1b0e-ac9f-4632-b4d7-7a68c594a001)
