### ISSUE TITLE
approval of external submitted listings

### ISSUE THREAD

**Issue by claratee** [ResilienceWeb/resilience-web#206]
https://resilienceweb.org.uk/admin
click on review and then approve of a pending listing
expected:  changes status
actual: listing item remains at the top of the list as pending

example is sustainable cottenham.

500 error reported in inspector for PUT https://resilienceweb.org.uk/api/listings/sustainable-cottenham

**Comment by DinerIsmail** [comment]
@claratee this is now fixed, thank you very much for reporting!
