### ISSUE TITLE
Remove unpopulated categories in tag view and web view

### ISSUE THREAD

**Issue by bitmask** [ResilienceWeb/resilience-web#233]
When viewing the web with a tag eg:
https://cambridge-city.resilienceweb.org.uk/?tags=A+penny+saved&web=1

Actual: Categories that do not contain entries with the selected tag will be shown, but will be unpopulated.  In the above example there are nodes for Union, Art, Conservation, but there are no entries connected to these nodes. 

Expected: Hide unpopulated category nodes in web view.

**Comment by DinerIsmail** [comment]
Thank you @bitmask, this is fixed now ✅
