### ISSUE TITLE
New entry form description does not allow pasting

### ISSUE THREAD

**Issue by claratee** [ResilienceWeb/resilience-web#244]
Trying to add description to a new listing, via the suggest feature on a mobile. 
Repro:
On mobile, 
1 Have text on clipboard
2 Go to https://cambridge-city.resilienceweb.org.uk/
3 Click propose a new listing button
4 Tab to description field and long click to bring up menu

Expected: see controls that Includes paste
Actual: A "link.." popover appears instead

![Screenshot_20241214-125252](https://github.com/user-attachments/assets/6a2817a9-a5af-4877-9f83-585ca3f0981b)

**Comment by DinerIsmail** [comment]
Thank you @claratee, I've fixed this now ✅
